apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
  annotations:
    cloud.google.com/neg: '{"ingress": true, "exposed_ports": {"3500":{}}}'
    cloud.google.com/backend-config: '{"default": "api-backend-config"}'
spec:
  selector:
    role: api  # Ensure this matches the labels in your pods
  ports:
  - name: http  # Add a name to the port (optional but recommended)
    port: 3500  # Port to expose the service on
    targetPort: 3500  # Container's port to route traffic to
    protocol: TCP
  type: ClusterIP
