apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - port: 3000
    protocol: TCP
  type: ClusterIP
  selector:
    role: frontend